### ISSUE TITLE
Satzzeichen in § 2

### ISSUE THREAD

**Issue by exploide** [d120/vereinssatzung#2]
In § 2 Abs. 3 a) fehlt ein Satzzeichen. Ich gehe davon aus, dass das Komma bei b) beabsichtigt ist?! Demnach würde ein solches bei a) fehlen.

Bei § 6 hingegen findet sich eine ähnliche Auflistung, deren Teilsätze jedoch mit Punkten enden. Ggf. konsistent machen.

**Comment by spilot** [comment]
Der neuste commit fixt.
