### ISSUE TITLE
Logo auf Satzungdeckblatt

### ISSUE THREAD

**Issue by exploide** [d120/vereinssatzung#3]
Da ja demnächst ggf. das Logo der Fachschaft geändert wird, ist es eher ungünstig das Wesen auf das Deckblatt der Satzung zu drucken. Potentiell eher weglassen. Der Meinung sind auch @ObviouslyNot, Julius und Tobi.

**Comment by matedealer** [comment]
me too

**Comment by spilot** [comment]
New commit fixes.

**Comment by max-weller** [comment]
vorher war's schöner ...

**Comment by spilot** [comment]
Ja, ich finde auch sowohl die Satzung als auch den Antrag auf Mitgliedschaft mit Wesen schöner. Beuge mich hier nur dem Willen der Allgemeinheit.

**Comment by jlauinger** [comment]
![](https://t2.ftcdn.net/jpg/00/35/46/83/400_F_35468305_ED2Je28kA2C4Couxt62iwzQcjozvY5ac.jpg)
